# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Build and E2E Test

on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    if: |
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            # https://github.com/microsoft/playwright/issues/11932
            E2E: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn test:e2e:ci
          - os: macos-latest
            E2E: yarn test:e2e:ci
          - os: windows-latest
            E2E: yarn test:e2e:ci

    steps:
      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@v2 # use hash or @vX here (See note below)
        if: matrix.os == 'ubuntu-latest'
        with:
          task: start-measurement

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 20

      - run: yarn install --immutable

      - name: Checkout and Installation Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v2 # use hash or @vX here (See note below)
        if: matrix.os == 'ubuntu-latest'
        with:
          task: get-measurement
          label: 'checkout and installation'

      - run: yarn ship:auto

      - run: yarn spdx

      - name: Build release Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v2 # use hash or @vX here (See note below)
        if: matrix.os == 'ubuntu-latest'
        with:
          task: get-measurement
          label: 'build release'

      - run: ${{ matrix.E2E }}

      - name: E2E CI Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v2 # use hash or @vX here (See note below)
        if: matrix.os == 'ubuntu-latest'
        with:
          task: get-measurement
          label: 'e2e ci test'

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: artifacts
          path: src/e2e-tests/artifacts
          retention-days: 30

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@v2 # use hash or @vX here (See note below)
        if: matrix.os == 'ubuntu-latest'
        with:
          task: display-results
          pr-comment: true
